apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: efnjaujwt-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/efnjaujwt-dotnet-basic-gitops